/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PayRouteImport } from './routes/pay'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as OrderIndexRouteImport } from './routes/order/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as OrderStatusRouteImport } from './routes/order/status'
import { Route as AuthenticatedStoreSettingsRouteImport } from './routes/_authenticated/store-settings'
import { Route as AuthenticatedStaffMgmtRouteImport } from './routes/_authenticated/staff-mgmt'
import { Route as AuthenticatedShopDesignRouteImport } from './routes/_authenticated/shop-design'
import { Route as AuthenticatedRemarksRouteImport } from './routes/_authenticated/remarks'
import { Route as AuthenticatedPrintersRouteImport } from './routes/_authenticated/printers'
import { Route as AuthenticatedPaymentMethodsRouteImport } from './routes/_authenticated/payment-methods'
import { Route as AuthenticatedOpLogRouteImport } from './routes/_authenticated/op-log'
import { Route as AuthenticatedBizSwitchRouteImport } from './routes/_authenticated/biz-switch'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedWmsIndexRouteImport } from './routes/_authenticated/wms/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTimeslotsIndexRouteImport } from './routes/_authenticated/timeslots/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedTablesIndexRouteImport } from './routes/_authenticated/tables/index'
import { Route as AuthenticatedStockIndexRouteImport } from './routes/_authenticated/stock/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedRecipesIndexRouteImport } from './routes/_authenticated/recipes/index'
import { Route as AuthenticatedRechargePlansIndexRouteImport } from './routes/_authenticated/recharge-plans/index'
import { Route as AuthenticatedPromotionsIndexRouteImport } from './routes/_authenticated/promotions/index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders/index'
import { Route as AuthenticatedMembersIndexRouteImport } from './routes/_authenticated/members/index'
import { Route as AuthenticatedMaterialCostIndexRouteImport } from './routes/_authenticated/material-cost/index'
import { Route as AuthenticatedLevelsIndexRouteImport } from './routes/_authenticated/levels/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedCouponsIndexRouteImport } from './routes/_authenticated/coupons/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedCategoriesIndexRouteImport } from './routes/_authenticated/categories/index'
import { Route as AuthenticatedCashierIndexRouteImport } from './routes/_authenticated/cashier/index'
import { Route as AuthenticatedAreasIndexRouteImport } from './routes/_authenticated/areas/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedAddonsIndexRouteImport } from './routes/_authenticated/addons/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedReportsSalesRouteImport } from './routes/_authenticated/reports/sales'
import { Route as AuthenticatedReportsProductsRouteImport } from './routes/_authenticated/reports/products'
import { Route as AuthenticatedReportsPaymentsRouteImport } from './routes/_authenticated/reports/payments'
import { Route as AuthenticatedFinanceExpenseRouteImport } from './routes/_authenticated/finance/expense'
import { Route as AuthenticatedFinanceDamageRouteImport } from './routes/_authenticated/finance/damage'
import { Route as AuthenticatedFinanceAccountRouteImport } from './routes/_authenticated/finance/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'

const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIndexRoute = OrderIndexRouteImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OrderStatusRoute = OrderStatusRouteImport.update({
  id: '/order/status',
  path: '/order/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStoreSettingsRoute =
  AuthenticatedStoreSettingsRouteImport.update({
    id: '/store-settings',
    path: '/store-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffMgmtRoute = AuthenticatedStaffMgmtRouteImport.update({
  id: '/staff-mgmt',
  path: '/staff-mgmt',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShopDesignRoute = AuthenticatedShopDesignRouteImport.update({
  id: '/shop-design',
  path: '/shop-design',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemarksRoute = AuthenticatedRemarksRouteImport.update({
  id: '/remarks',
  path: '/remarks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrintersRoute = AuthenticatedPrintersRouteImport.update({
  id: '/printers',
  path: '/printers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentMethodsRoute =
  AuthenticatedPaymentMethodsRouteImport.update({
    id: '/payment-methods',
    path: '/payment-methods',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpLogRoute = AuthenticatedOpLogRouteImport.update({
  id: '/op-log',
  path: '/op-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBizSwitchRoute = AuthenticatedBizSwitchRouteImport.update({
  id: '/biz-switch',
  path: '/biz-switch',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWmsIndexRoute = AuthenticatedWmsIndexRouteImport.update({
  id: '/wms/',
  path: '/wms/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimeslotsIndexRoute =
  AuthenticatedTimeslotsIndexRouteImport.update({
    id: '/timeslots/',
    path: '/timeslots/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTablesIndexRoute =
  AuthenticatedTablesIndexRouteImport.update({
    id: '/tables/',
    path: '/tables/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockIndexRoute = AuthenticatedStockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedRecipesIndexRoute =
  AuthenticatedRecipesIndexRouteImport.update({
    id: '/recipes/',
    path: '/recipes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRechargePlansIndexRoute =
  AuthenticatedRechargePlansIndexRouteImport.update({
    id: '/recharge-plans/',
    path: '/recharge-plans/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPromotionsIndexRoute =
  AuthenticatedPromotionsIndexRouteImport.update({
    id: '/promotions/',
    path: '/promotions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembersIndexRoute =
  AuthenticatedMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialCostIndexRoute =
  AuthenticatedMaterialCostIndexRouteImport.update({
    id: '/material-cost/',
    path: '/material-cost/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLevelsIndexRoute =
  AuthenticatedLevelsIndexRouteImport.update({
    id: '/levels/',
    path: '/levels/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCouponsIndexRoute =
  AuthenticatedCouponsIndexRouteImport.update({
    id: '/coupons/',
    path: '/coupons/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriesIndexRoute =
  AuthenticatedCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCashierIndexRoute =
  AuthenticatedCashierIndexRouteImport.update({
    id: '/cashier/',
    path: '/cashier/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAreasIndexRoute = AuthenticatedAreasIndexRouteImport.update({
  id: '/areas/',
  path: '/areas/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAddonsIndexRoute =
  AuthenticatedAddonsIndexRouteImport.update({
    id: '/addons/',
    path: '/addons/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedReportsSalesRoute =
  AuthenticatedReportsSalesRouteImport.update({
    id: '/reports/sales',
    path: '/reports/sales',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsProductsRoute =
  AuthenticatedReportsProductsRouteImport.update({
    id: '/reports/products',
    path: '/reports/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsPaymentsRoute =
  AuthenticatedReportsPaymentsRouteImport.update({
    id: '/reports/payments',
    path: '/reports/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceExpenseRoute =
  AuthenticatedFinanceExpenseRouteImport.update({
    id: '/finance/expense',
    path: '/finance/expense',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceDamageRoute =
  AuthenticatedFinanceDamageRouteImport.update({
    id: '/finance/damage',
    path: '/finance/damage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceAccountRoute =
  AuthenticatedFinanceAccountRouteImport.update({
    id: '/finance/account',
    path: '/finance/account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/pay': typeof PayRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/biz-switch': typeof AuthenticatedBizSwitchRoute
  '/op-log': typeof AuthenticatedOpLogRoute
  '/payment-methods': typeof AuthenticatedPaymentMethodsRoute
  '/printers': typeof AuthenticatedPrintersRoute
  '/remarks': typeof AuthenticatedRemarksRoute
  '/shop-design': typeof AuthenticatedShopDesignRoute
  '/staff-mgmt': typeof AuthenticatedStaffMgmtRoute
  '/store-settings': typeof AuthenticatedStoreSettingsRoute
  '/order/status': typeof OrderStatusRoute
  '/order/': typeof OrderIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/finance/account': typeof AuthenticatedFinanceAccountRoute
  '/finance/damage': typeof AuthenticatedFinanceDamageRoute
  '/finance/expense': typeof AuthenticatedFinanceExpenseRoute
  '/reports/payments': typeof AuthenticatedReportsPaymentsRoute
  '/reports/products': typeof AuthenticatedReportsProductsRoute
  '/reports/sales': typeof AuthenticatedReportsSalesRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/addons/': typeof AuthenticatedAddonsIndexRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/areas/': typeof AuthenticatedAreasIndexRoute
  '/cashier/': typeof AuthenticatedCashierIndexRoute
  '/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/coupons/': typeof AuthenticatedCouponsIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/levels/': typeof AuthenticatedLevelsIndexRoute
  '/material-cost/': typeof AuthenticatedMaterialCostIndexRoute
  '/members/': typeof AuthenticatedMembersIndexRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/promotions/': typeof AuthenticatedPromotionsIndexRoute
  '/recharge-plans/': typeof AuthenticatedRechargePlansIndexRoute
  '/recipes/': typeof AuthenticatedRecipesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/stock/': typeof AuthenticatedStockIndexRoute
  '/tables/': typeof AuthenticatedTablesIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/timeslots/': typeof AuthenticatedTimeslotsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/wms/': typeof AuthenticatedWmsIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/pay': typeof PayRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/biz-switch': typeof AuthenticatedBizSwitchRoute
  '/op-log': typeof AuthenticatedOpLogRoute
  '/payment-methods': typeof AuthenticatedPaymentMethodsRoute
  '/printers': typeof AuthenticatedPrintersRoute
  '/remarks': typeof AuthenticatedRemarksRoute
  '/shop-design': typeof AuthenticatedShopDesignRoute
  '/staff-mgmt': typeof AuthenticatedStaffMgmtRoute
  '/store-settings': typeof AuthenticatedStoreSettingsRoute
  '/order/status': typeof OrderStatusRoute
  '/': typeof AuthenticatedIndexRoute
  '/order': typeof OrderIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/finance/account': typeof AuthenticatedFinanceAccountRoute
  '/finance/damage': typeof AuthenticatedFinanceDamageRoute
  '/finance/expense': typeof AuthenticatedFinanceExpenseRoute
  '/reports/payments': typeof AuthenticatedReportsPaymentsRoute
  '/reports/products': typeof AuthenticatedReportsProductsRoute
  '/reports/sales': typeof AuthenticatedReportsSalesRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/addons': typeof AuthenticatedAddonsIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/areas': typeof AuthenticatedAreasIndexRoute
  '/cashier': typeof AuthenticatedCashierIndexRoute
  '/categories': typeof AuthenticatedCategoriesIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/coupons': typeof AuthenticatedCouponsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/levels': typeof AuthenticatedLevelsIndexRoute
  '/material-cost': typeof AuthenticatedMaterialCostIndexRoute
  '/members': typeof AuthenticatedMembersIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/promotions': typeof AuthenticatedPromotionsIndexRoute
  '/recharge-plans': typeof AuthenticatedRechargePlansIndexRoute
  '/recipes': typeof AuthenticatedRecipesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/stock': typeof AuthenticatedStockIndexRoute
  '/tables': typeof AuthenticatedTablesIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/timeslots': typeof AuthenticatedTimeslotsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/wms': typeof AuthenticatedWmsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/pay': typeof PayRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/biz-switch': typeof AuthenticatedBizSwitchRoute
  '/_authenticated/op-log': typeof AuthenticatedOpLogRoute
  '/_authenticated/payment-methods': typeof AuthenticatedPaymentMethodsRoute
  '/_authenticated/printers': typeof AuthenticatedPrintersRoute
  '/_authenticated/remarks': typeof AuthenticatedRemarksRoute
  '/_authenticated/shop-design': typeof AuthenticatedShopDesignRoute
  '/_authenticated/staff-mgmt': typeof AuthenticatedStaffMgmtRoute
  '/_authenticated/store-settings': typeof AuthenticatedStoreSettingsRoute
  '/order/status': typeof OrderStatusRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/order/': typeof OrderIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/finance/account': typeof AuthenticatedFinanceAccountRoute
  '/_authenticated/finance/damage': typeof AuthenticatedFinanceDamageRoute
  '/_authenticated/finance/expense': typeof AuthenticatedFinanceExpenseRoute
  '/_authenticated/reports/payments': typeof AuthenticatedReportsPaymentsRoute
  '/_authenticated/reports/products': typeof AuthenticatedReportsProductsRoute
  '/_authenticated/reports/sales': typeof AuthenticatedReportsSalesRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/addons/': typeof AuthenticatedAddonsIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/areas/': typeof AuthenticatedAreasIndexRoute
  '/_authenticated/cashier/': typeof AuthenticatedCashierIndexRoute
  '/_authenticated/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/coupons/': typeof AuthenticatedCouponsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/levels/': typeof AuthenticatedLevelsIndexRoute
  '/_authenticated/material-cost/': typeof AuthenticatedMaterialCostIndexRoute
  '/_authenticated/members/': typeof AuthenticatedMembersIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/promotions/': typeof AuthenticatedPromotionsIndexRoute
  '/_authenticated/recharge-plans/': typeof AuthenticatedRechargePlansIndexRoute
  '/_authenticated/recipes/': typeof AuthenticatedRecipesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/stock/': typeof AuthenticatedStockIndexRoute
  '/_authenticated/tables/': typeof AuthenticatedTablesIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/timeslots/': typeof AuthenticatedTimeslotsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/wms/': typeof AuthenticatedWmsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/pay'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/biz-switch'
    | '/op-log'
    | '/payment-methods'
    | '/printers'
    | '/remarks'
    | '/shop-design'
    | '/staff-mgmt'
    | '/store-settings'
    | '/order/status'
    | '/order/'
    | '/errors/$error'
    | '/finance/account'
    | '/finance/damage'
    | '/finance/expense'
    | '/reports/payments'
    | '/reports/products'
    | '/reports/sales'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/addons/'
    | '/apps/'
    | '/areas/'
    | '/cashier/'
    | '/categories/'
    | '/chats/'
    | '/coupons/'
    | '/help-center/'
    | '/levels/'
    | '/material-cost/'
    | '/members/'
    | '/orders/'
    | '/products/'
    | '/promotions/'
    | '/recharge-plans/'
    | '/recipes/'
    | '/settings/'
    | '/stock/'
    | '/tables/'
    | '/tasks/'
    | '/timeslots/'
    | '/users/'
    | '/wms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/pay'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/biz-switch'
    | '/op-log'
    | '/payment-methods'
    | '/printers'
    | '/remarks'
    | '/shop-design'
    | '/staff-mgmt'
    | '/store-settings'
    | '/order/status'
    | '/'
    | '/order'
    | '/errors/$error'
    | '/finance/account'
    | '/finance/damage'
    | '/finance/expense'
    | '/reports/payments'
    | '/reports/products'
    | '/reports/sales'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/addons'
    | '/apps'
    | '/areas'
    | '/cashier'
    | '/categories'
    | '/chats'
    | '/coupons'
    | '/help-center'
    | '/levels'
    | '/material-cost'
    | '/members'
    | '/orders'
    | '/products'
    | '/promotions'
    | '/recharge-plans'
    | '/recipes'
    | '/settings'
    | '/stock'
    | '/tables'
    | '/tasks'
    | '/timeslots'
    | '/users'
    | '/wms'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/pay'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/biz-switch'
    | '/_authenticated/op-log'
    | '/_authenticated/payment-methods'
    | '/_authenticated/printers'
    | '/_authenticated/remarks'
    | '/_authenticated/shop-design'
    | '/_authenticated/staff-mgmt'
    | '/_authenticated/store-settings'
    | '/order/status'
    | '/_authenticated/'
    | '/order/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/finance/account'
    | '/_authenticated/finance/damage'
    | '/_authenticated/finance/expense'
    | '/_authenticated/reports/payments'
    | '/_authenticated/reports/products'
    | '/_authenticated/reports/sales'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/addons/'
    | '/_authenticated/apps/'
    | '/_authenticated/areas/'
    | '/_authenticated/cashier/'
    | '/_authenticated/categories/'
    | '/_authenticated/chats/'
    | '/_authenticated/coupons/'
    | '/_authenticated/help-center/'
    | '/_authenticated/levels/'
    | '/_authenticated/material-cost/'
    | '/_authenticated/members/'
    | '/_authenticated/orders/'
    | '/_authenticated/products/'
    | '/_authenticated/promotions/'
    | '/_authenticated/recharge-plans/'
    | '/_authenticated/recipes/'
    | '/_authenticated/settings/'
    | '/_authenticated/stock/'
    | '/_authenticated/tables/'
    | '/_authenticated/tasks/'
    | '/_authenticated/timeslots/'
    | '/_authenticated/users/'
    | '/_authenticated/wms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  PayRoute: typeof PayRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  OrderStatusRoute: typeof OrderStatusRoute
  OrderIndexRoute: typeof OrderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/': {
      id: '/order/'
      path: '/order'
      fullPath: '/order/'
      preLoaderRoute: typeof OrderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/order/status': {
      id: '/order/status'
      path: '/order/status'
      fullPath: '/order/status'
      preLoaderRoute: typeof OrderStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/store-settings': {
      id: '/_authenticated/store-settings'
      path: '/store-settings'
      fullPath: '/store-settings'
      preLoaderRoute: typeof AuthenticatedStoreSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff-mgmt': {
      id: '/_authenticated/staff-mgmt'
      path: '/staff-mgmt'
      fullPath: '/staff-mgmt'
      preLoaderRoute: typeof AuthenticatedStaffMgmtRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shop-design': {
      id: '/_authenticated/shop-design'
      path: '/shop-design'
      fullPath: '/shop-design'
      preLoaderRoute: typeof AuthenticatedShopDesignRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/remarks': {
      id: '/_authenticated/remarks'
      path: '/remarks'
      fullPath: '/remarks'
      preLoaderRoute: typeof AuthenticatedRemarksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/printers': {
      id: '/_authenticated/printers'
      path: '/printers'
      fullPath: '/printers'
      preLoaderRoute: typeof AuthenticatedPrintersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment-methods': {
      id: '/_authenticated/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof AuthenticatedPaymentMethodsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op-log': {
      id: '/_authenticated/op-log'
      path: '/op-log'
      fullPath: '/op-log'
      preLoaderRoute: typeof AuthenticatedOpLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biz-switch': {
      id: '/_authenticated/biz-switch'
      path: '/biz-switch'
      fullPath: '/biz-switch'
      preLoaderRoute: typeof AuthenticatedBizSwitchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wms/': {
      id: '/_authenticated/wms/'
      path: '/wms'
      fullPath: '/wms/'
      preLoaderRoute: typeof AuthenticatedWmsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timeslots/': {
      id: '/_authenticated/timeslots/'
      path: '/timeslots'
      fullPath: '/timeslots/'
      preLoaderRoute: typeof AuthenticatedTimeslotsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tables/': {
      id: '/_authenticated/tables/'
      path: '/tables'
      fullPath: '/tables/'
      preLoaderRoute: typeof AuthenticatedTablesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock/': {
      id: '/_authenticated/stock/'
      path: '/stock'
      fullPath: '/stock/'
      preLoaderRoute: typeof AuthenticatedStockIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/recipes/': {
      id: '/_authenticated/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AuthenticatedRecipesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recharge-plans/': {
      id: '/_authenticated/recharge-plans/'
      path: '/recharge-plans'
      fullPath: '/recharge-plans/'
      preLoaderRoute: typeof AuthenticatedRechargePlansIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promotions/': {
      id: '/_authenticated/promotions/'
      path: '/promotions'
      fullPath: '/promotions/'
      preLoaderRoute: typeof AuthenticatedPromotionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members/': {
      id: '/_authenticated/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof AuthenticatedMembersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material-cost/': {
      id: '/_authenticated/material-cost/'
      path: '/material-cost'
      fullPath: '/material-cost/'
      preLoaderRoute: typeof AuthenticatedMaterialCostIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/levels/': {
      id: '/_authenticated/levels/'
      path: '/levels'
      fullPath: '/levels/'
      preLoaderRoute: typeof AuthenticatedLevelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coupons/': {
      id: '/_authenticated/coupons/'
      path: '/coupons'
      fullPath: '/coupons/'
      preLoaderRoute: typeof AuthenticatedCouponsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories/': {
      id: '/_authenticated/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AuthenticatedCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cashier/': {
      id: '/_authenticated/cashier/'
      path: '/cashier'
      fullPath: '/cashier/'
      preLoaderRoute: typeof AuthenticatedCashierIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/areas/': {
      id: '/_authenticated/areas/'
      path: '/areas'
      fullPath: '/areas/'
      preLoaderRoute: typeof AuthenticatedAreasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/addons/': {
      id: '/_authenticated/addons/'
      path: '/addons'
      fullPath: '/addons/'
      preLoaderRoute: typeof AuthenticatedAddonsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/reports/sales': {
      id: '/_authenticated/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof AuthenticatedReportsSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/products': {
      id: '/_authenticated/reports/products'
      path: '/reports/products'
      fullPath: '/reports/products'
      preLoaderRoute: typeof AuthenticatedReportsProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/payments': {
      id: '/_authenticated/reports/payments'
      path: '/reports/payments'
      fullPath: '/reports/payments'
      preLoaderRoute: typeof AuthenticatedReportsPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/expense': {
      id: '/_authenticated/finance/expense'
      path: '/finance/expense'
      fullPath: '/finance/expense'
      preLoaderRoute: typeof AuthenticatedFinanceExpenseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/damage': {
      id: '/_authenticated/finance/damage'
      path: '/finance/damage'
      fullPath: '/finance/damage'
      preLoaderRoute: typeof AuthenticatedFinanceDamageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/account': {
      id: '/_authenticated/finance/account'
      path: '/finance/account'
      fullPath: '/finance/account'
      preLoaderRoute: typeof AuthenticatedFinanceAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedBizSwitchRoute: typeof AuthenticatedBizSwitchRoute
  AuthenticatedOpLogRoute: typeof AuthenticatedOpLogRoute
  AuthenticatedPaymentMethodsRoute: typeof AuthenticatedPaymentMethodsRoute
  AuthenticatedPrintersRoute: typeof AuthenticatedPrintersRoute
  AuthenticatedRemarksRoute: typeof AuthenticatedRemarksRoute
  AuthenticatedShopDesignRoute: typeof AuthenticatedShopDesignRoute
  AuthenticatedStaffMgmtRoute: typeof AuthenticatedStaffMgmtRoute
  AuthenticatedStoreSettingsRoute: typeof AuthenticatedStoreSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedFinanceAccountRoute: typeof AuthenticatedFinanceAccountRoute
  AuthenticatedFinanceDamageRoute: typeof AuthenticatedFinanceDamageRoute
  AuthenticatedFinanceExpenseRoute: typeof AuthenticatedFinanceExpenseRoute
  AuthenticatedReportsPaymentsRoute: typeof AuthenticatedReportsPaymentsRoute
  AuthenticatedReportsProductsRoute: typeof AuthenticatedReportsProductsRoute
  AuthenticatedReportsSalesRoute: typeof AuthenticatedReportsSalesRoute
  AuthenticatedAddonsIndexRoute: typeof AuthenticatedAddonsIndexRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedAreasIndexRoute: typeof AuthenticatedAreasIndexRoute
  AuthenticatedCashierIndexRoute: typeof AuthenticatedCashierIndexRoute
  AuthenticatedCategoriesIndexRoute: typeof AuthenticatedCategoriesIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedCouponsIndexRoute: typeof AuthenticatedCouponsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedLevelsIndexRoute: typeof AuthenticatedLevelsIndexRoute
  AuthenticatedMaterialCostIndexRoute: typeof AuthenticatedMaterialCostIndexRoute
  AuthenticatedMembersIndexRoute: typeof AuthenticatedMembersIndexRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedPromotionsIndexRoute: typeof AuthenticatedPromotionsIndexRoute
  AuthenticatedRechargePlansIndexRoute: typeof AuthenticatedRechargePlansIndexRoute
  AuthenticatedRecipesIndexRoute: typeof AuthenticatedRecipesIndexRoute
  AuthenticatedStockIndexRoute: typeof AuthenticatedStockIndexRoute
  AuthenticatedTablesIndexRoute: typeof AuthenticatedTablesIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedTimeslotsIndexRoute: typeof AuthenticatedTimeslotsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWmsIndexRoute: typeof AuthenticatedWmsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedBizSwitchRoute: AuthenticatedBizSwitchRoute,
  AuthenticatedOpLogRoute: AuthenticatedOpLogRoute,
  AuthenticatedPaymentMethodsRoute: AuthenticatedPaymentMethodsRoute,
  AuthenticatedPrintersRoute: AuthenticatedPrintersRoute,
  AuthenticatedRemarksRoute: AuthenticatedRemarksRoute,
  AuthenticatedShopDesignRoute: AuthenticatedShopDesignRoute,
  AuthenticatedStaffMgmtRoute: AuthenticatedStaffMgmtRoute,
  AuthenticatedStoreSettingsRoute: AuthenticatedStoreSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedFinanceAccountRoute: AuthenticatedFinanceAccountRoute,
  AuthenticatedFinanceDamageRoute: AuthenticatedFinanceDamageRoute,
  AuthenticatedFinanceExpenseRoute: AuthenticatedFinanceExpenseRoute,
  AuthenticatedReportsPaymentsRoute: AuthenticatedReportsPaymentsRoute,
  AuthenticatedReportsProductsRoute: AuthenticatedReportsProductsRoute,
  AuthenticatedReportsSalesRoute: AuthenticatedReportsSalesRoute,
  AuthenticatedAddonsIndexRoute: AuthenticatedAddonsIndexRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedAreasIndexRoute: AuthenticatedAreasIndexRoute,
  AuthenticatedCashierIndexRoute: AuthenticatedCashierIndexRoute,
  AuthenticatedCategoriesIndexRoute: AuthenticatedCategoriesIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedCouponsIndexRoute: AuthenticatedCouponsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedLevelsIndexRoute: AuthenticatedLevelsIndexRoute,
  AuthenticatedMaterialCostIndexRoute: AuthenticatedMaterialCostIndexRoute,
  AuthenticatedMembersIndexRoute: AuthenticatedMembersIndexRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedPromotionsIndexRoute: AuthenticatedPromotionsIndexRoute,
  AuthenticatedRechargePlansIndexRoute: AuthenticatedRechargePlansIndexRoute,
  AuthenticatedRecipesIndexRoute: AuthenticatedRecipesIndexRoute,
  AuthenticatedStockIndexRoute: AuthenticatedStockIndexRoute,
  AuthenticatedTablesIndexRoute: AuthenticatedTablesIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedTimeslotsIndexRoute: AuthenticatedTimeslotsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWmsIndexRoute: AuthenticatedWmsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  PayRoute: PayRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  OrderStatusRoute: OrderStatusRoute,
  OrderIndexRoute: OrderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
